services:
  db:
    image: postgres:17-alpine
    container_name: RATAC_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RATAC_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DB/schema:/docker-entrypoint-initdb.d:ro,Z # ro,Z agregado por problemas especificos de Fedora

  app:
    build: 
      context: .
      target: builder # Durante desarrollo usamos la etapa pesada para poder recompilar
    container_name: RATAC_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/RATAC_DB
    volumes:
      - .:/app:Z # Esto sincroniza tus archivos locales con el contenedor
    command: >
      sh -c "templ generate && 
             sqlc generate && 
             go run ." 

volumes:
  postgres_data:
