// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package DB

import (
	"database/sql"
	"time"
)

type DescripcionesMicroscopica struct {
	Descripcion        string         `json:"descripcion"`
	Diagnostico        sql.NullString `json:"diagnostico"`
	PacientesProtocolo string         `json:"pacientes_protocolo"`
}

type GradoOncologico struct {
	Caracteristica                               string         `json:"caracteristica"`
	MuestraAnalizada                             sql.NullString `json:"muestra_analizada"`
	Puntaje                                      int16          `json:"puntaje"`
	Total                                        int16          `json:"total"`
	DescripcionesMicroscopicasDescripcion        string         `json:"descripciones_microscopicas_descripcion"`
	DescripcionesMicroscopicasPacientesProtocolo string         `json:"descripciones_microscopicas_pacientes_protocolo"`
}

type Imagene struct {
	Ruta                                         string `json:"ruta"`
	DescripcionesMicroscopicasDescripcion        string `json:"descripciones_microscopicas_descripcion"`
	DescripcionesMicroscopicasPacientesProtocolo string `json:"descripciones_microscopicas_pacientes_protocolo"`
}

type Paciente struct {
	ID                      int32          `json:"id"`
	Protocolo               string         `json:"protocolo"`
	Fecha                   time.Time      `json:"fecha"`
	Solicitante             string         `json:"solicitante"`
	Tecnica                 string         `json:"tecnica"`
	Familia                 sql.NullString `json:"familia"`
	Especie                 sql.NullString `json:"especie"`
	Raza                    sql.NullString `json:"raza"`
	Edad                    sql.NullInt16  `json:"edad"`
	Paciente                string         `json:"paciente"`
	Antecedentes            sql.NullString `json:"antecedentes"`
	DescripcionMacroscopica sql.NullString `json:"descripcion_macroscopica"`
	ReferenciasMastocitomas bool           `json:"referencias_mastocitomas"`
}
