// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package DB

import (
	"context"
	"database/sql"
	"time"
)

const createDescripcionMicroscopica = `-- name: CreateDescripcionMicroscopica :one
INSERT INTO Descripciones_microscopicas (
    Descripcion, Diagnostico, Pacientes_Protocolo
) VALUES (
    $1, $2, $3
)
RETURNING descripcion, diagnostico, pacientes_protocolo
`

type CreateDescripcionMicroscopicaParams struct {
	Descripcion        string         `json:"descripcion"`
	Diagnostico        sql.NullString `json:"diagnostico"`
	PacientesProtocolo string         `json:"pacientes_protocolo"`
}

func (q *Queries) CreateDescripcionMicroscopica(ctx context.Context, arg CreateDescripcionMicroscopicaParams) (DescripcionesMicroscopica, error) {
	row := q.db.QueryRowContext(ctx, createDescripcionMicroscopica, arg.Descripcion, arg.Diagnostico, arg.PacientesProtocolo)
	var i DescripcionesMicroscopica
	err := row.Scan(&i.Descripcion, &i.Diagnostico, &i.PacientesProtocolo)
	return i, err
}

const createImagen = `-- name: CreateImagen :one
INSERT INTO Imagenes (
    Ruta, Descripciones_microscopicas_Descripcion, Descripciones_microscopicas_Pacientes_Protocolo
) VALUES (
    $1, $2, $3
)
RETURNING ruta, descripciones_microscopicas_descripcion, descripciones_microscopicas_pacientes_protocolo
`

type CreateImagenParams struct {
	Ruta                                         string `json:"ruta"`
	DescripcionesMicroscopicasDescripcion        string `json:"descripciones_microscopicas_descripcion"`
	DescripcionesMicroscopicasPacientesProtocolo string `json:"descripciones_microscopicas_pacientes_protocolo"`
}

func (q *Queries) CreateImagen(ctx context.Context, arg CreateImagenParams) (Imagene, error) {
	row := q.db.QueryRowContext(ctx, createImagen, arg.Ruta, arg.DescripcionesMicroscopicasDescripcion, arg.DescripcionesMicroscopicasPacientesProtocolo)
	var i Imagene
	err := row.Scan(&i.Ruta, &i.DescripcionesMicroscopicasDescripcion, &i.DescripcionesMicroscopicasPacientesProtocolo)
	return i, err
}

const createPaciente = `-- name: CreatePaciente :one
INSERT INTO Pacientes (
    Protocolo, Fecha, Solicitante, Tecnica, Familia, 
    Especie, Raza, Edad, Paciente, Antecedentes, 
    Descripcion_macroscopica, Referencias_mastocitomas
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, protocolo, fecha, solicitante, tecnica, familia, especie, raza, edad, paciente, antecedentes, descripcion_macroscopica, referencias_mastocitomas
`

type CreatePacienteParams struct {
	Protocolo               string         `json:"protocolo"`
	Fecha                   time.Time      `json:"fecha"`
	Solicitante             string         `json:"solicitante"`
	Tecnica                 string         `json:"tecnica"`
	Familia                 sql.NullString `json:"familia"`
	Especie                 sql.NullString `json:"especie"`
	Raza                    sql.NullString `json:"raza"`
	Edad                    sql.NullInt16  `json:"edad"`
	Paciente                string         `json:"paciente"`
	Antecedentes            sql.NullString `json:"antecedentes"`
	DescripcionMacroscopica sql.NullString `json:"descripcion_macroscopica"`
	ReferenciasMastocitomas bool           `json:"referencias_mastocitomas"`
}

func (q *Queries) CreatePaciente(ctx context.Context, arg CreatePacienteParams) (Paciente, error) {
	row := q.db.QueryRowContext(ctx, createPaciente,
		arg.Protocolo,
		arg.Fecha,
		arg.Solicitante,
		arg.Tecnica,
		arg.Familia,
		arg.Especie,
		arg.Raza,
		arg.Edad,
		arg.Paciente,
		arg.Antecedentes,
		arg.DescripcionMacroscopica,
		arg.ReferenciasMastocitomas,
	)
	var i Paciente
	err := row.Scan(
		&i.ID,
		&i.Protocolo,
		&i.Fecha,
		&i.Solicitante,
		&i.Tecnica,
		&i.Familia,
		&i.Especie,
		&i.Raza,
		&i.Edad,
		&i.Paciente,
		&i.Antecedentes,
		&i.DescripcionMacroscopica,
		&i.ReferenciasMastocitomas,
	)
	return i, err
}

const deleteDescripcionMicroscopica = `-- name: DeleteDescripcionMicroscopica :exec
DELETE FROM Descripciones_microscopicas
WHERE Descripcion = $1 AND Pacientes_Protocolo = $2
`

type DeleteDescripcionMicroscopicaParams struct {
	Descripcion        string `json:"descripcion"`
	PacientesProtocolo string `json:"pacientes_protocolo"`
}

func (q *Queries) DeleteDescripcionMicroscopica(ctx context.Context, arg DeleteDescripcionMicroscopicaParams) error {
	_, err := q.db.ExecContext(ctx, deleteDescripcionMicroscopica, arg.Descripcion, arg.PacientesProtocolo)
	return err
}

const deleteImagen = `-- name: DeleteImagen :exec
DELETE FROM Imagenes
WHERE Ruta = $1
`

func (q *Queries) DeleteImagen(ctx context.Context, ruta string) error {
	_, err := q.db.ExecContext(ctx, deleteImagen, ruta)
	return err
}

const deletePaciente = `-- name: DeletePaciente :exec
DELETE FROM Pacientes
WHERE Protocolo = $1
`

func (q *Queries) DeletePaciente(ctx context.Context, protocolo string) error {
	_, err := q.db.ExecContext(ctx, deletePaciente, protocolo)
	return err
}

const getDescripcionByPaciente = `-- name: GetDescripcionByPaciente :many
SELECT descripcion, diagnostico, pacientes_protocolo FROM Descripciones_microscopicas
WHERE Pacientes_Protocolo = $1
`

func (q *Queries) GetDescripcionByPaciente(ctx context.Context, pacientesProtocolo string) ([]DescripcionesMicroscopica, error) {
	rows, err := q.db.QueryContext(ctx, getDescripcionByPaciente, pacientesProtocolo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DescripcionesMicroscopica
	for rows.Next() {
		var i DescripcionesMicroscopica
		if err := rows.Scan(&i.Descripcion, &i.Diagnostico, &i.PacientesProtocolo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGradoOncologico = `-- name: GetGradoOncologico :one
SELECT caracteristica, muestra_analizada, puntaje, total, descripciones_microscopicas_descripcion, descripciones_microscopicas_pacientes_protocolo FROM Grado_oncologico
WHERE Descripciones_microscopicas_Pacientes_Protocolo = $1
AND Descripciones_microscopicas_Descripcion = $2
`

type GetGradoOncologicoParams struct {
	DescripcionesMicroscopicasPacientesProtocolo string `json:"descripciones_microscopicas_pacientes_protocolo"`
	DescripcionesMicroscopicasDescripcion        string `json:"descripciones_microscopicas_descripcion"`
}

func (q *Queries) GetGradoOncologico(ctx context.Context, arg GetGradoOncologicoParams) (GradoOncologico, error) {
	row := q.db.QueryRowContext(ctx, getGradoOncologico, arg.DescripcionesMicroscopicasPacientesProtocolo, arg.DescripcionesMicroscopicasDescripcion)
	var i GradoOncologico
	err := row.Scan(
		&i.Caracteristica,
		&i.MuestraAnalizada,
		&i.Puntaje,
		&i.Total,
		&i.DescripcionesMicroscopicasDescripcion,
		&i.DescripcionesMicroscopicasPacientesProtocolo,
	)
	return i, err
}

const getImagenesByDescripcion = `-- name: GetImagenesByDescripcion :many
SELECT ruta, descripciones_microscopicas_descripcion, descripciones_microscopicas_pacientes_protocolo FROM Imagenes
WHERE Descripciones_microscopicas_Descripcion = $1 
AND Descripciones_microscopicas_Pacientes_Protocolo = $2
`

type GetImagenesByDescripcionParams struct {
	DescripcionesMicroscopicasDescripcion        string `json:"descripciones_microscopicas_descripcion"`
	DescripcionesMicroscopicasPacientesProtocolo string `json:"descripciones_microscopicas_pacientes_protocolo"`
}

func (q *Queries) GetImagenesByDescripcion(ctx context.Context, arg GetImagenesByDescripcionParams) ([]Imagene, error) {
	rows, err := q.db.QueryContext(ctx, getImagenesByDescripcion, arg.DescripcionesMicroscopicasDescripcion, arg.DescripcionesMicroscopicasPacientesProtocolo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Imagene
	for rows.Next() {
		var i Imagene
		if err := rows.Scan(&i.Ruta, &i.DescripcionesMicroscopicasDescripcion, &i.DescripcionesMicroscopicasPacientesProtocolo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaciente = `-- name: GetPaciente :one
SELECT id, protocolo, fecha, solicitante, tecnica, familia, especie, raza, edad, paciente, antecedentes, descripcion_macroscopica, referencias_mastocitomas FROM Pacientes
WHERE Protocolo = $1 LIMIT 1
`

func (q *Queries) GetPaciente(ctx context.Context, protocolo string) (Paciente, error) {
	row := q.db.QueryRowContext(ctx, getPaciente, protocolo)
	var i Paciente
	err := row.Scan(
		&i.ID,
		&i.Protocolo,
		&i.Fecha,
		&i.Solicitante,
		&i.Tecnica,
		&i.Familia,
		&i.Especie,
		&i.Raza,
		&i.Edad,
		&i.Paciente,
		&i.Antecedentes,
		&i.DescripcionMacroscopica,
		&i.ReferenciasMastocitomas,
	)
	return i, err
}

const listPacientes = `-- name: ListPacientes :many
SELECT id, protocolo, fecha, solicitante, tecnica, familia, especie, raza, edad, paciente, antecedentes, descripcion_macroscopica, referencias_mastocitomas FROM Pacientes
ORDER BY Fecha DESC
`

func (q *Queries) ListPacientes(ctx context.Context) ([]Paciente, error) {
	rows, err := q.db.QueryContext(ctx, listPacientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paciente
	for rows.Next() {
		var i Paciente
		if err := rows.Scan(
			&i.ID,
			&i.Protocolo,
			&i.Fecha,
			&i.Solicitante,
			&i.Tecnica,
			&i.Familia,
			&i.Especie,
			&i.Raza,
			&i.Edad,
			&i.Paciente,
			&i.Antecedentes,
			&i.DescripcionMacroscopica,
			&i.ReferenciasMastocitomas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDescripcionMicroscopica = `-- name: UpdateDescripcionMicroscopica :one
UPDATE Descripciones_microscopicas
SET Diagnostico = $3
WHERE Descripcion = $1 AND Pacientes_Protocolo = $2
RETURNING descripcion, diagnostico, pacientes_protocolo
`

type UpdateDescripcionMicroscopicaParams struct {
	Descripcion        string         `json:"descripcion"`
	PacientesProtocolo string         `json:"pacientes_protocolo"`
	Diagnostico        sql.NullString `json:"diagnostico"`
}

func (q *Queries) UpdateDescripcionMicroscopica(ctx context.Context, arg UpdateDescripcionMicroscopicaParams) (DescripcionesMicroscopica, error) {
	row := q.db.QueryRowContext(ctx, updateDescripcionMicroscopica, arg.Descripcion, arg.PacientesProtocolo, arg.Diagnostico)
	var i DescripcionesMicroscopica
	err := row.Scan(&i.Descripcion, &i.Diagnostico, &i.PacientesProtocolo)
	return i, err
}

const updateGradoOncologico = `-- name: UpdateGradoOncologico :one
UPDATE Grado_oncologico
SET 
    Caracteristica = $3,
    Muestra_analizada = $4,
    Puntaje = $5,
    Total = $6
WHERE Descripciones_microscopicas_Pacientes_Protocolo = $1
AND Descripciones_microscopicas_Descripcion = $2
RETURNING caracteristica, muestra_analizada, puntaje, total, descripciones_microscopicas_descripcion, descripciones_microscopicas_pacientes_protocolo
`

type UpdateGradoOncologicoParams struct {
	DescripcionesMicroscopicasPacientesProtocolo string         `json:"descripciones_microscopicas_pacientes_protocolo"`
	DescripcionesMicroscopicasDescripcion        string         `json:"descripciones_microscopicas_descripcion"`
	Caracteristica                               string         `json:"caracteristica"`
	MuestraAnalizada                             sql.NullString `json:"muestra_analizada"`
	Puntaje                                      int16          `json:"puntaje"`
	Total                                        int16          `json:"total"`
}

func (q *Queries) UpdateGradoOncologico(ctx context.Context, arg UpdateGradoOncologicoParams) (GradoOncologico, error) {
	row := q.db.QueryRowContext(ctx, updateGradoOncologico,
		arg.DescripcionesMicroscopicasPacientesProtocolo,
		arg.DescripcionesMicroscopicasDescripcion,
		arg.Caracteristica,
		arg.MuestraAnalizada,
		arg.Puntaje,
		arg.Total,
	)
	var i GradoOncologico
	err := row.Scan(
		&i.Caracteristica,
		&i.MuestraAnalizada,
		&i.Puntaje,
		&i.Total,
		&i.DescripcionesMicroscopicasDescripcion,
		&i.DescripcionesMicroscopicasPacientesProtocolo,
	)
	return i, err
}

const updatePaciente = `-- name: UpdatePaciente :one
UPDATE Pacientes
SET 
    Fecha = $2,
    Solicitante = $3,
    Tecnica = $4,
    Familia = $5,
    Especie = $6,
    Raza = $7,
    Edad = $8,
    Paciente = $9,
    Antecedentes = $10,
    Descripcion_macroscopica = $11,
    Referencias_mastocitomas = $12
WHERE Protocolo = $1
RETURNING id, protocolo, fecha, solicitante, tecnica, familia, especie, raza, edad, paciente, antecedentes, descripcion_macroscopica, referencias_mastocitomas
`

type UpdatePacienteParams struct {
	Protocolo               string         `json:"protocolo"`
	Fecha                   time.Time      `json:"fecha"`
	Solicitante             string         `json:"solicitante"`
	Tecnica                 string         `json:"tecnica"`
	Familia                 sql.NullString `json:"familia"`
	Especie                 sql.NullString `json:"especie"`
	Raza                    sql.NullString `json:"raza"`
	Edad                    sql.NullInt16  `json:"edad"`
	Paciente                string         `json:"paciente"`
	Antecedentes            sql.NullString `json:"antecedentes"`
	DescripcionMacroscopica sql.NullString `json:"descripcion_macroscopica"`
	ReferenciasMastocitomas bool           `json:"referencias_mastocitomas"`
}

func (q *Queries) UpdatePaciente(ctx context.Context, arg UpdatePacienteParams) (Paciente, error) {
	row := q.db.QueryRowContext(ctx, updatePaciente,
		arg.Protocolo,
		arg.Fecha,
		arg.Solicitante,
		arg.Tecnica,
		arg.Familia,
		arg.Especie,
		arg.Raza,
		arg.Edad,
		arg.Paciente,
		arg.Antecedentes,
		arg.DescripcionMacroscopica,
		arg.ReferenciasMastocitomas,
	)
	var i Paciente
	err := row.Scan(
		&i.ID,
		&i.Protocolo,
		&i.Fecha,
		&i.Solicitante,
		&i.Tecnica,
		&i.Familia,
		&i.Especie,
		&i.Raza,
		&i.Edad,
		&i.Paciente,
		&i.Antecedentes,
		&i.DescripcionMacroscopica,
		&i.ReferenciasMastocitomas,
	)
	return i, err
}
